<a href="https://colab.research.google.com/github/Aya-Elgammal/Python_Project-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<font color='86A788'>**Numpy<span class='label label-default'></span>**</font>

In [1]:
import numpy as np

<font color='F4D793' size='3'>**Creating Numpy Arrays**</font>

In [2]:
#Creating a 1D Numpy Array from a List
my_list = [1,2,3,4,5,6,7,8]
my_list = np.array(my_list)
print(f"My Array : {my_list}")

My Array : [1 2 3 4 5 6 7 8]


In [3]:
#N-dimensional arrays
sales_data = np.array([
    [[150, 200, 500], [400, 350, 350]],  # Week 1
    [[230, 110, 210], [210, 360, 360]],  # Week 2
    [[270, 320, 420], [220, 270, 370]],  # Week 3
    [[280, 330, 430], [220, 250, 380]]   # Week 4
])#list of muli list
print(f"3D Array:\n {sales_data}")
print(f"Shape: {sales_data.shape}")

# Axis 0: Weeks (4 weeks).
# Axis 1: Regions (2 regions).
# Axis 2: Products (3 products).

3D Array:
 [[[150 200 500]
  [400 350 350]]

 [[230 110 210]
  [210 360 360]]

 [[270 320 420]
  [220 270 370]]

 [[280 330 430]
  [220 250 380]]]
Shape: (4, 2, 3)


In [4]:
#Creating a 2D Numpy Array from a List of Lists
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
#This creates a two-dimensional Numpy array arr from a list of lists.

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#Creating an Array of Zeros
zeros_arr = np.zeros((3,3))
print(f"Zeros Array :\n {zeros_arr}")
#This creates a 3x3 Numpy array filled with zeros.

Zeros Array :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Creating an Array of Ones
ones_arr = np.ones((3,3))
print(f"Ones Array :\n {ones_arr}")
#This creates a 3x2 Numpy array filled with ones.

Ones Array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#Creating an Array with a Specific Range
range_array = np.arange(1,11)
print(f"Range Array : {range_array}")
#This creates a 1D Numpy array with values from 1 to 10.

Range Array : [ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#Creating an Array with a Range of Values and Specific Step Size
range_array = np.arange(1,21,3)
print(f"Range Array : {range_array}")
#This creates an array with values starting from 1 up to 19, with a step size of 2.

Range Array : [ 1  4  7 10 13 16 19]


In [9]:
#Creating an Array of Evenly Spaced Values Between Two Numbers
linspace_array = np.linspace(0,1,10)
print(f"Linspace Array :\n {linspace_array}")
#This creates an array of 10 evenly spaced values between 0 and 1.

Linspace Array :
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
#Creating an Array with Random Values Between 0 and 1
random_array = np.random.rand(4,4)
print(f"Random Array : \n{random_array}")
#This creates a 4x4 array with random floating-point numbers between 0 and 1

Random Array : 
[[0.95712169 0.69189464 0.98133623 0.93640732]
 [0.19193551 0.96937741 0.46413897 0.06996448]
 [0.58260028 0.89407303 0.09480473 0.91248675]
 [0.62457998 0.79179316 0.13570288 0.90029092]]


In [11]:
#Creating an Array with Random Integers
random_array_int = np.random.randint(1,20,(4,4))
print(f"Random Integer Array : \n{random_array_int}")
#This creates a 4x4 array with random integers between 1 and 18

Random Integer Array : 
[[ 8 16  7 11]
 [ 4  2  8  8]
 [ 3 15 17  2]
 [ 2  8  9 11]]


In [12]:
#Checking the Shape of an Array
print(arr.shape)
#This returns the shape of the array, showing it has 2 rows and 4 columns.

(2, 4)


In [13]:
#Accessing Data Type of Elements
print(arr.dtype)
#This checks the data type of elements in the array, showing that they are 64-bit integers

int64


In [14]:
#Indexing a 1D Array
print (f"First Element in Array : {my_list[0]},Last Element in Array : {my_list[-1]},Fourth Element in Array: {my_list[3]}")

First Element in Array : 1,Last Element in Array : 8,Fourth Element in Array: 4


In [15]:
#Slicing a 1D Array
print(f"First Four Elements in Array : {my_list[0:4]}")
#This slices the array to get a subarray from index 1 to 3

First Four Elements in Array : [1 2 3 4]


In [16]:
#Indexing a 2D Array
print(arr[0:2,1:])
#This slices the array to get a subarray from 0 to row 1 and columns 1 to the end

[[2 3 4]
 [6 7 8]]


<font color='F4D793' size='3'>**Indexing a 2D Array (matrices)**</font>

In [17]:
#Indexing a 2D Array (matrices)
mat = np.array(([5,10,20],[20,25,30],[34,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [34, 40, 10]])

In [18]:
#Indexing a row
print(f"mat[1] = {mat[1]} , mat[2] = {mat[2]}")

mat[1] = [20 25 30] , mat[2] = [34 40 10]


In [19]:
#Geting individual values
print(f"mat[1][1] = {mat[1][1]}")

mat[1][1] = 25


In [20]:
#Geting individual values
print(f"mat[1,1] = {mat[1,1]}")

mat[1,1] = 25


In [21]:
#Find top right corner
mat[:2,1:]

array([[10, 20],
       [25, 30]])

In [22]:
#Find bottom left corner
mat[1:,:2]

array([[20, 25],
       [34, 40]])

In [23]:
#shape botton row
mat[2,:]

array([34, 40, 10])

<font color='86A788' size='3'>**Slicing a 2D Array**</font>

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(f"a = \n {a}")

a = 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
#geting specific element [r,c]
a[1,4]

12

In [26]:
#geting specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#geting specific columns
a[:,0]

array([1, 8])

In [28]:
#geting more fancy
a[0,1:-1:2]

array([2, 4, 6])

<font color='86A788' size='3'>**Boolean Array Indexing**</font>

In [29]:
a = np.arange(1, 11)

In [30]:
#Applying a Boolean Condition
print(f" if a >  4 : \n{a >  4}")

 if a >  4 : 
[False False False False  True  True  True  True  True  True]


In [31]:
#Storing the Boolean Mask
bool_A = a > 4
print(bool_A)

[False False False False  True  True  True  True  True  True]


In [32]:
#Using Boolean Indexing
a[bool_A]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
# Applying Another Example with a >= 2
print(f" if a >= 2 : \n{a >= 2}")

 if a >= 2 : 
[False  True  True  True  True  True  True  True  True  True]


<font color='F4D793' size='3'>**Creating Numpy Arrays**</font>

In [34]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(f"arr1 + arr2 = \n {arr1+arr2}")

arr1 + arr2 = 
 [ 6  8 10 12]


In [35]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(f"X =\n {x},\n Y =\n {y}")

X =
 [[1. 2.]
 [3. 4.]],
 Y =
 [[5. 6.]
 [7. 8.]]


In [36]:
#Element-wise Addition
print("X + Y = \n",x + y)
print("Add Function = \n",np.add(x, y))

X + Y = 
 [[ 6.  8.]
 [10. 12.]]
Add Function = 
 [[ 6.  8.]
 [10. 12.]]


In [37]:
#Element-wise Subtraction
print("X - Y = \n",x - y)
print("Subtract Function = \n",np.subtract(x, y))

X - Y = 
 [[-4. -4.]
 [-4. -4.]]
Subtract Function = 
 [[-4. -4.]
 [-4. -4.]]


In [38]:
#Element-wise Multiplication
print("X * Y = \n",x * y)
print("Multiply Function = \n",np.multiply(x, y))

X * Y = 
 [[ 5. 12.]
 [21. 32.]]
Multiply Function = 
 [[ 5. 12.]
 [21. 32.]]


In [39]:
#Element-wise Division
print("X / Y = \n",x / y)
print("Divide Function = \n",np.divide(x, y))

X / Y = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Divide Function = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [40]:
#Dot Product
np.dot(x, y)

array([[19., 22.],
       [43., 50.]])

<font color='F4D793' size='3'>**Array Broadcasting**</font>

In [41]:
print(x+10)

[[11. 12.]
 [13. 14.]]


In [42]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
print(y)

[[33508613582           0           0]
 [          0           0           0]
 [          0           0           0]
 [          0           0           0]]


In [43]:
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [44]:
y = x + v
print(x,"\n*************\n",y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
*************
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [45]:
print(np.max(arr))
print(np.min(arr))

8
1


<font color='86A788' size='3'>**quiz_time_**</font>

In [46]:
arr3 = np.arange(1, 31).reshape(6, 5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [47]:
arr3[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [48]:
arr[0:1,3:]

array([[4]])

In [49]:
arr[4:,3:]

array([], shape=(0, 1), dtype=int64)

In [50]:
arr3[:] = 0
arr3[[0, 1, 2, 3], [1, 1, 1, 1]] = [2, 8, 14, 20]
arr3

array([[ 0,  2,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0, 14,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])